-- ============================================================================
-- Sample Images Data with Unsplash URLs
-- ============================================================================
-- This script populates the Image table with sample hotel images
-- Embeddings are left NULL and should be generated via Python script later
-- or by the image search service on first upload

-- Check if images already exist (idempotent)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM "Image" WHERE image_url LIKE 'https://images.unsplash.com%' LIMIT 1) THEN

        -- Insert sample images for hotels
        INSERT INTO "Image" (
            image_url,
            hotel_id,
            room_id,
            destination_id,
            image_description,
            image_tags,
            image_width,
            image_height,
            image_format,
            embedding_model,
            image_embedding,
            embedding_created_at,
            created_at,
            updated_at
        ) VALUES
        -- Hoan Kiem Lake sunset (Destination image)
        (
            'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80',
            NULL,
            NULL,
            1,  -- Hanoi destination
            'Beautiful sunset view over Hoan Kiem Lake in Hanoi with golden sky and peaceful water',
            ARRAY['sunset', 'lake', 'hanoi', 'peaceful', 'golden'],
            800,
            600,
            'jpg',
            NULL,  -- Model name will be set when embedding is generated
            NULL,  -- Embedding will be generated by Python script
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        ),
        -- Golden Bridge Vietnam
        (
            'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&q=80',
            NULL,
            NULL,
            2,  -- Da Nang destination
            'Golden Bridge at Ba Na Hills held by giant stone hands with mountain views',
            ARRAY['bridge', 'golden', 'danang', 'mountain', 'architecture'],
            800,
            600,
            'jpg',
            NULL,
            NULL,
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        ),
        -- Hanoi Grand Hotel - Luxury lobby
        (
            'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80',
            1,  -- Hanoi Grand Hotel
            NULL,
            NULL,
            'Luxurious hotel lobby with modern furniture and elegant design in Hanoi',
            ARRAY['lobby', 'luxury', 'modern', 'elegant', 'interior'],
            800,
            600,
            'jpg',
            NULL,
            NULL,
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        ),
        -- Hanoi Grand Hotel - Rooftop pool
        (
            'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800&q=80',
            1,
            NULL,
            NULL,
            'Rooftop swimming pool with panoramic views of Hanoi city skyline at sunset',
            ARRAY['pool', 'rooftop', 'sunset', 'cityview', 'panoramic'],
            800,
            600,
            'jpg',
            NULL,
            NULL,
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        ),
        -- Hanoi Grand Hotel - Fine dining restaurant
        (
            'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80',
            1,
            NULL,
            NULL,
            'Fine dining restaurant with Vietnamese and international cuisine, elegant interior design',
            ARRAY['restaurant', 'dining', 'luxury', 'food', 'elegant'],
            800,
            600,
            'jpg',
            NULL,
            NULL,
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        ),
        -- Da Nang Beach Resort - Infinity pool
        (
            'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
            2,  -- Da Nang Beach Resort
            NULL,
            NULL,
            'Infinity pool overlooking the ocean with blue water and beachfront views in Da Nang',
            ARRAY['pool', 'infinity', 'ocean', 'beach', 'blue'],
            800,
            600,
            'jpg',
            NULL,
            NULL,
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        ),
        -- Da Nang Beach Resort - Private beach
        (
            'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&q=80',
            2,
            NULL,
            NULL,
            'Private beach access with white sand and crystal clear blue ocean water',
            ARRAY['beach', 'ocean', 'sand', 'tropical', 'clear water'],
            800,
            600,
            'jpg',
            NULL,
            NULL,
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        ),
        -- Da Nang Beach Resort - Deluxe ocean view room
        (
            'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80',
            2,
            NULL,
            NULL,
            'Deluxe ocean view room with king size bed and private balcony overlooking the sea',
            ARRAY['room', 'bedroom', 'ocean view', 'balcony', 'king bed'],
            800,
            600,
            'jpg',
            NULL,
            NULL,
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        ),
        -- Saigon Luxury Hotel - Presidential suite
        (
            'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800&q=80',
            3,  -- Saigon Luxury Hotel (assuming ID 3 exists)
            NULL,
            NULL,
            'Presidential suite with separate living area, luxury furniture and city views',
            ARRAY['suite', 'luxury', 'living room', 'premium', 'city view'],
            800,
            600,
            'jpg',
            NULL,
            NULL,
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        ),
        -- Saigon Luxury Hotel - Spa
        (
            'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80',
            3,
            NULL,
            NULL,
            'Modern spa and wellness center with massage rooms and relaxation area',
            ARRAY['spa', 'wellness', 'massage', 'relaxation', 'modern'],
            800,
            600,
            'jpg',
            NULL,
            NULL,
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        ),
        -- Modern hotel room interior
        (
            'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80',
            1,
            NULL,
            NULL,
            'Modern hotel room with comfortable bed, work desk, and city views',
            ARRAY['room', 'modern', 'comfortable', 'desk', 'city view'],
            800,
            600,
            'jpg',
            NULL,
            NULL,
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        ),
        -- Luxury suite living room
        (
            'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
            2,
            NULL,
            NULL,
            'Spacious suite living room with luxury furniture and large windows',
            ARRAY['suite', 'living room', 'luxury', 'spacious', 'windows'],
            800,
            600,
            'jpg',
            NULL,
            NULL,
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        ),
        -- Mountain resort view
        (
            'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
            NULL,
            NULL,
            4,  -- Mountain destination (if exists)
            'Mountain resort with stunning valley views and green nature surroundings',
            ARRAY['mountain', 'nature', 'valley', 'resort', 'green'],
            800,
            600,
            'jpg',
            NULL,
            NULL,
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        ),
        -- Tropical resort pool
        (
            'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
            NULL,
            NULL,
            3,  -- Beach destination
            'Tropical resort infinity pool surrounded by palm trees and ocean views',
            ARRAY['pool', 'infinity', 'tropical', 'palm trees', 'ocean'],
            800,
            600,
            'jpg',
            NULL,
            NULL,
            NULL,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        )
        ON CONFLICT DO NOTHING;

        RAISE NOTICE '✅ Inserted % sample images with Unsplash URLs', 14;
        RAISE NOTICE '⚠️  Embeddings are NULL - run populate_image_embeddings.py to generate CLIP embeddings';
    ELSE
        RAISE NOTICE '⏭️  Sample images already exist, skipping insertion';
    END IF;
END $$;
